#! /bin/bash


if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    timer=timeout
else #Assuming mac OS
    timer=gtimeout
fi

output=$(date "+%d-%m-%y_%H:%M:%S.log")
commande=../bin/resol
cflags=""
temps=20s
echo "========== Sans flags =============" > "$output"
for x in *.cnf; do
    echo "/////// $x //////// " >> "$output"
    ligne=$((time ($timer $temps $commande $x) )2>&1)
    result=$(echo "$ligne" | grep SAT)
    reel=$(echo "$ligne" | grep real)
    user=$(echo "$ligne" | grep user)
    sys=$(echo "$ligne" | grep sys)
    if [ -n "$result" ]; then
        echo $result >> "$output"
    else
        echo TIME LIMIT EXEDEED >> "$output"
    fi
    echo $reel | (read name value; echo "$value") >> "$output"
    echo $user | (read name value; echo "$value") >> "$output"
    echo $sys  | (read name value; echo "$value") >> "$output"
done ;

for cflags in -moms -dlis -rand -wl; do
    echo "========== Avec $cflags =============" >> "$output"
    for x in *.cnf; do
        echo " ////// $x /////// " >> "$output"
        ligne=$((time ($timer $temps $commande $cflags $x) )2>&1)
        result=$(echo "$ligne" | grep SAT)
        reel=$(echo "$ligne" | grep real)
        user=$(echo "$ligne" | grep user)
        sys=$(echo "$ligne" | grep sys)
        if [ -n "$result" ]; then
            echo $result >> "$output"
        else
            echo TIME LIMIT EXEDEED >> "$output"
        fi
        echo $reel | (read name value; echo "$value") >> "$output"
        echo $user | (read name value; echo "$value") >> "$output"
        echo $sys  | (read name value; echo "$value") >> "$output"
    done ;
done ;
