#! /bin/bash

d=$(date +%x)
h=$(date +%X)
outp="$d"_"$h".log
commande=../bin/resol
cflags=""
temps=20s
output=$(echo "$outp" | sed -e "s/\//-/g")
timeout="timeout"

echo "========== Sans flags =============" > "$output"
for x in *.cnf; do
    echo "/////// $x //////// " >> "$output"
    ligne=$((time ($timeout $temps $commande $x) )2>&1)
    result=$(echo "$ligne" | grep SAT)
    reel=$(echo "$ligne" | grep real)
    user=$(echo "$ligne" | grep user)
    sys=$(echo "$ligne" | grep sys)
    if [ -n "$result" ]; then
        echo $result >> "$output"
    else
        echo TIME LIMIT EXCEEDED >> "$output"
    fi
    echo $reel | (read name value; echo "$value") >> "$output"
    echo $user | (read name value; echo "$value") >> "$output"
    echo $sys  | (read name value; echo "$value") >> "$output"
done ;

for cflags in -moms -dlis -rand -wl; do
    echo "========== Avec $cflags =============" >> "$output"
    for x in *.cnf; do
        echo " ////// $x /////// " >> "$output"
        ligne=$((time ($timeout $temps $commande $cflags $x) )2>&1)
        result=$(echo "$ligne" | grep SAT)
        reel=$(echo "$ligne" | grep real)
        user=$(echo "$ligne" | grep user)
        sys=$(echo "$ligne" | grep sys)
        if [ -n "$result" ]; then
            echo $result >> "$output"
        else
            echo TIME LIMIT EXCEEDED >> "$output"
        fi
        echo $reel | (read name value; echo "$value") >> "$output"
        echo $user | (read name value; echo "$value") >> "$output"
        echo $sys  | (read name value; echo "$value") >> "$output"
    done ;
done ;
